name = "berlin-beer-food"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "BERLIN_KV"
id = "a513fa12615545018118fc1f4b639e38"
preview_id = "c907d2e1ad2f4716aaf5fde823c42cb8"
